version: 0.2
phases:
	install:
    runtime-versions:
      java: openjdk8
  pre-build:
    commands:
    - echo "Entered the pre-build phase"
     - java -version
      - mvn package
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean package
  post-build:
    commands:
    - echo "Entered the post-build phase"
    
artifacts:
  files:
    - '**/*'
  base-directory: 'target/my-web-app'
