version: 0.2
phases:
  pre-build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean package
  post-build:
    commands:
    - echo "Entered the post-build phase"
    
